language: rust
matrix:
  include:
    - rust: stable
      env: FEATURES='std'
    - rust: beta
      env: FEATURES='std'
    - rust: nightly
      env: FEATURES=''
    - rust: nightly
      env: FEATURES='alloc'
    - rust: nightly
      env: FEATURES='collections'
    - rust: nightly
      env: FEATURES='alloc collections'
    - rust: nightly
      env: FEATURES='std alloc collections'
script:
   - cargo build --no-default-features --features "$FEATURES"
notifications:
  irc:
    channels:
      - "chat.freenode.net#m-labs"
    use_notice: true
    skip_join: true
